# Generated by Django 5.2.1 on 2025-05-23 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('categoria_estrellas', models.PositiveSmallIntegerField()),
                ('descripcion_general', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'hoteles',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('servicio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=50)),
                ('descripcion_servicio', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('tipo_habitacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('capacidad_max', models.PositiveIntegerField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'tipos_habitacion',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('habitacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_habitacion', models.CharField(max_length=10)),
                ('precio_por_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='Disponible', max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.hotel')),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.tipohabitacion')),
            ],
            options={
                'db_table': 'habitaciones',
                'unique_together': {('hotel', 'numero_habitacion')},
            },
        ),
        migrations.CreateModel(
            name='RoomServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.habitacion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.servicio')),
            ],
            options={
                'db_table': 'room_servicios',
                'unique_together': {('habitacion', 'servicio')},
            },
        ),
        migrations.CreateModel(
            name='HotelServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.hotel')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.servicio')),
            ],
            options={
                'db_table': 'hotel_servicios',
                'unique_together': {('hotel', 'servicio')},
            },
        ),
    ]
