# Generated by Django 5.2.1 on 2025-05-23 06:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('users', '0003_cliente_rol_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('promocion_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_promo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('descuento_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('descuento_fijo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'promociones',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('factura_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado_pago', models.CharField(default='Pendiente', max_length=20)),
                ('empleado_emisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.empleado')),
            ],
            options={
                'db_table': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='ItemFactura',
            fields=[
                ('item_factura_id', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.factura')),
            ],
            options={
                'db_table': 'items_factura',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.factura')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('reserva_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_checkin', models.DateField()),
                ('fecha_checkout', models.DateField()),
                ('numero_adultos', models.PositiveIntegerField()),
                ('numero_ninos', models.PositiveIntegerField(default=0)),
                ('estado_reserva', models.CharField(default='Pendiente', max_length=20)),
                ('costo_total_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cliente')),
                ('empleado_checkin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_reservas', to='users.empleado')),
                ('empleado_checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_reservas', to='users.empleado')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.habitacion')),
            ],
            options={
                'db_table': 'reservas',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reserva'),
        ),
        migrations.CreateModel(
            name='ReservaPromociones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.promocion')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reserva')),
            ],
            options={
                'db_table': 'reserva_promociones',
                'unique_together': {('reserva', 'promocion')},
            },
        ),
    ]
